// @vitest-environment jsdom

import { beforeEach, describe, expect, it } from "vitest";
import { scrapeBuiltInJob } from "../src/adapters/builtin.js";
import { scrapeDiceJob } from "../src/adapters/dice.js";
import { scrapeIndeedJob } from "../src/adapters/indeed.js";
import { scrapeLinkedInJob } from "../src/adapters/linkedin.js";

function jsonLd(value) {
  document.body.innerHTML += `<script type="application/ld+json">${JSON.stringify(value)}</script>`;
}

describe("multi-site adapters", () => {
  beforeEach(() => {
    document.head.innerHTML = "";
    document.body.innerHTML = "";
  });

  it("extracts an Indeed job from matching structured data", () => {
    document.body.innerHTML = `
      <h1>Quality Assurance Engineer</h1>
      <div id="salaryInfoAndJobType">$145,000 - $160,000 a year</div>
      <aside>Similar job: $57,000 - $65,000 a year</aside>`;
    jsonLd({
      "@context": "https://schema.org",
      "@type": "JobPosting",
      url: "https://www.indeed.com/viewjob?jk=24577bb1f38ccee8",
      title: "Quality Assurance Engineer",
      hiringOrganization: { name: "Xpansiv" },
      jobLocationType: "TELECOMMUTE",
      applicantLocationRequirements: { name: "United States" },
      baseSalary: { value: { minValue: 145000, maxValue: 160000, unitText: "YEAR" } },
      description: "<p>At least 5 years of experience are required.</p><ul><li>Build reliable tests</li></ul>",
    });

    const result = scrapeIndeedJob({
      document,
      url: "https://www.indeed.com/viewjob?jk=24577bb1f38ccee8&from=serp",
    });
    expect(result.ok).toBe(true);
    expect(result.data).toMatchObject({
      company: "Xpansiv",
      role_title: "Quality Assurance Engineer",
      source: "Indeed",
      location: "Remote (United States)",
      years_experience_min: 5,
      salary_min: 145000,
      salary_max: 160000,
    });
    expect(result.data.job_link).toBe("https://www.indeed.com/viewjob?jk=24577bb1f38ccee8");
  });

  it("extracts Built In data without using its generated summary", () => {
    document.body.innerHTML = `
      <main><h1>Senior Quality Assurance Engineer</h1><p>120K-120K Annually</p></main>
      <section><h2>The Role</h2><p>Summary Generated by Built In: invented summary.</p></section>
      <section><h2>The Company</h2><span>1,200 Employees</span></section>`;
    jsonLd({
      "@context": "https://schema.org",
      "@graph": [{
        "@type": "JobPosting",
        url: "https://builtin.com/job/senior-quality-assurance-engineer/7166800",
        title: "Senior Quality Assurance Engineer",
        hiringOrganization: { name: "Corporate Tools LLC" },
        jobLocationType: "TELECOMMUTE",
        applicantLocationRequirements: { name: "United States" },
        baseSalary: { value: { minValue: 120000, maxValue: 120000, unitText: "YEAR" } },
        description: "<p>You will lead QA efforts.</p><p>Minimum 7 years of experience required.</p>",
      }],
    });

    const result = scrapeBuiltInJob({
      document,
      url: "https://builtin.com/job/senior-quality-assurance-engineer/7166800?utm_source=test",
    });
    expect(result.data).toMatchObject({
      company: "Corporate Tools LLC",
      company_size: "massive",
      years_experience_min: 7,
      salary_min: 120000,
      salary_max: 120000,
    });
    expect(result.data.job_description).not.toContain("Generated by Built In");
  });

  it("matches the current Dice UUID and ignores Similar Jobs", () => {
    document.body.innerHTML = `
      <h1>Accreditation Data Coordination Analyst</h1>
      <section><h2>Similar Jobs</h2><p>Senior QA Engineer $190k-$220k</p></section>`;
    jsonLd({
      "@type": "JobPosting",
      identifier: { value: "65aaf8e9-0d93-4438-a9d4-fc70c04458d0" },
      title: "Accreditation Data Coordination Analyst",
      hiringOrganization: { name: "BlueCross BlueShield Of South Carolina" },
      jobLocation: { address: { addressLocality: "Columbia", addressRegion: "SC", addressCountry: "US" } },
      description: "<p>Coordinate accreditation data quality and reporting.</p>",
    });

    const result = scrapeDiceJob({
      document,
      url: "https://www.dice.com/job-detail/65aaf8e9-0d93-4438-a9d4-fc70c04458d0",
    });
    expect(result.data).toMatchObject({
      company: "BlueCross BlueShield Of South Carolina",
      source: "Dice",
      location: "Columbia, SC, US",
      salary_min: null,
      salary_max: null,
    });
  });

  it("keeps hourly Dice pay and records the period (KAN-52)", () => {
    document.body.innerHTML = "<h1>Automation Engineer</h1>";
    jsonLd({
      "@type": "JobPosting",
      identifier: { value: "be7caab2-4852-44bc-8f41-d1a40bde0ba8" },
      title: "Automation Engineer",
      hiringOrganization: { name: "Example Staffing" },
      baseSalary: { value: { minValue: 60, maxValue: 70, unitText: "HOUR" } },
      description: "<p>Build test automation.</p>",
    });
    const result = scrapeDiceJob({
      document,
      url: "https://www.dice.com/job-detail/be7caab2-4852-44bc-8f41-d1a40bde0ba8",
    });
    // This used to assert the opposite. The tracker had one pair of salary
    // columns and no way to say what they measured, so a correctly parsed
    // hourly rate was thrown away with a warning. KAN-50 added pay_period.
    expect(result.data.salary_min).toBe(60);
    expect(result.data.salary_max).toBe(70);
    expect(result.data.pay_period).toBe("hourly");
    // finalizeResult still warns about genuinely absent optional fields; what
    // must be gone is the pay warning.
    expect(result.warnings.join(" ")).not.toContain("cannot store");
    expect(result.warnings.join(" ")).not.toContain("Non-annual");
  });

  it("still refuses a period the tracker cannot store", () => {
    // A day rate has no home in the enum, so it is still discarded — and the
    // warning now means that specifically rather than "not annual".
    document.body.innerHTML = "<h1>Automation Engineer</h1>";
    jsonLd({
      "@type": "JobPosting",
      identifier: { value: "be7caab2-4852-44bc-8f41-d1a40bde0ba8" },
      title: "Automation Engineer",
      hiringOrganization: { name: "Example Staffing" },
      baseSalary: { value: { minValue: 500, maxValue: 600, unitText: "DAY" } },
      description: "<p>Build test automation.</p>",
    });
    const result = scrapeDiceJob({
      document,
      url: "https://www.dice.com/job-detail/be7caab2-4852-44bc-8f41-d1a40bde0ba8",
    });
    expect(result.data.salary_min).toBeNull();
    expect(result.warnings.join(" ")).toContain("cannot store");
  });

  it("maps schema.org employmentType onto the tracker enum", () => {
    document.body.innerHTML = "<h1>Automation Engineer</h1>";
    jsonLd({
      "@type": "JobPosting",
      identifier: { value: "be7caab2-4852-44bc-8f41-d1a40bde0ba8" },
      title: "Automation Engineer",
      hiringOrganization: { name: "Example Staffing" },
      employmentType: "CONTRACTOR",
      description: "<p>Commitment: 10-40 hrs/week.</p>",
    });
    const result = scrapeDiceJob({
      document,
      url: "https://www.dice.com/job-detail/be7caab2-4852-44bc-8f41-d1a40bde0ba8",
    });
    expect(result.data.employment_type).toBe("contract");
    expect(result.data.hours_per_week_min).toBe(10);
    expect(result.data.hours_per_week_max).toBe(40);
  });

  it("rejects Dice structured data for a different job UUID", () => {
    document.body.innerHTML = "<h1>Current job</h1>";
    jsonLd({
      "@type": "JobPosting",
      identifier: { value: "11111111-1111-1111-1111-111111111111" },
      title: "Related job",
      hiringOrganization: { name: "Wrong company" },
      description: "<p>Unrelated recommendation.</p>",
    });
    const result = scrapeDiceJob({
      document,
      url: "https://www.dice.com/job-detail/22222222-2222-2222-2222-222222222222",
    });
    expect(result.ok).toBe(false);
    expect(result.error).toContain("company or role title");
  });

  it("extracts a signed-in LinkedIn direct job from the active detail card", () => {
    document.title = "Senior Functional and Automation Tester | Infosys | LinkedIn";
    document.body.innerHTML = `
      <main>
        <section class="job-details-jobs-unified-top-card">
          <div class="job-details-jobs-unified-top-card__company-name">Infosys</div>
          <div class="job-details-jobs-unified-top-card__primary-description-container">United States · 2 days ago</div>
          <h1>Senior Functional and Automation Tester</h1><span>Remote</span>
        </section>
        <section class="jobs-description"><h2>About the job</h2>
          <div class="jobs-description-content__text"><p>At least 6 years of experience.</p><p>Plan and execute automated testing.</p><p>The estimated annual compensation range is $73,000 to $102,200.</p></div>
        </section>
        <section><h2>Similar jobs</h2><p>Unrelated role $115,000 - $130,000 a year</p></section>
      </main>`;

    const result = scrapeLinkedInJob({
      document,
      url: "https://www.linkedin.com/jobs/view/4454643971/?alternateChannel=search",
    });
    expect(result.data).toMatchObject({
      company: "Infosys",
      role_title: "Senior Functional and Automation Tester",
      job_link: "https://www.linkedin.com/jobs/view/4454643971/",
      source: "LinkedIn",
      location: "Remote (United States)",
      years_experience_min: 6,
      salary_min: 73000,
      salary_max: 102200,
    });
    expect(result.data.job_description).not.toContain("Similar jobs");
  });

  it("fails clearly on a LinkedIn authentication shell", () => {
    document.title = "Senior Tester | Example Co | LinkedIn";
    document.body.innerHTML = "<footer>LinkedIn Corporation</footer>";
    const result = scrapeLinkedInJob({
      document,
      url: "https://www.linkedin.com/jobs/view/4454643971/",
    });
    expect(result).toMatchObject({ ok: false, error: expect.stringContaining("not available") });
  });
});
